[project]
name = "tuto-autodoc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "furo>=2024.8.6",
    "numpy>=2.2.6",
    "sphinx>=8.1.3",
]
